//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keeps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Keeps()
        {
            this.KeepLogs = new HashSet<KeepLogs>();
        }
    
        public long ID { get; set; }
        public long UserID { get; set; }
        public string Title { get; set; }
        public string Data { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long KeepTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeepLogs> KeepLogs { get; set; }
        public virtual Users Users { get; set; }
        public virtual KeepTypes KeepTypes { get; set; }
    }
}
